% =========================================================================
%  第一型曲线积分（对弧长的曲线积分）的几何意义可视化
%  Geometric Meaning of the First Kind Curve Integral (Scalar Line Integral)
%
%  几何解释：
%    被积函数 f(x,y) 在曲线 L 上的第一型曲线积分 ∫_L f(x,y) ds，
%    等于以曲线 L 为准线、母线平行于 z 轴的"柱面( curtain / wall )"的面积。
%    该"墙"的底部落在 xy 平面的曲x线 L 上，顶部触及曲面 z = f(x,y)。
%
%  命名规范：驼峰命名法 (camelCase)
% =========================================================================
clear; clc; close all;

%% ── 参数设置 ──────────────────────────────────────────────────────────
nCurvePts   = 200;       % 曲线 L 上的采样点数
nGridRes    = 60;        % 曲面网格分辨率
nWallLayers = 40;        % 柱面"墙"的纵向分层数
tRange      = linspace(0, 2 * pi, nCurvePts);

%% ── 1. 定义 xy 平面上的积分路径 L ─────────────────────────────────────
%  曲线 L 的参数方程：x = t, y = sin(t)，呈现一段优美的正弦波
curveX = tRange;
curveY = sin(tRange);
curveZ = zeros(size(tRange));                     % L 在 xy 平面，z = 0

%% ── 2. 定义被积曲面 z = f(x, y) ────────────────────────────────────────
%  一个平缓起伏的曲面，有视觉层次感
fSurface = @(x, y) 3 + 0.5 * cos(x) + 0.2 * y .^ 2;

%  曲线 L 上各点在曲面上的对应高度（墙顶）
surfaceHeight = fSurface(curveX, curveY);

%% ── 3. 生成曲面网格数据（半透明顶盖） ──────────────────────────────────
xGridRange = linspace(min(curveX) - 0.5, max(curveX) + 0.5, nGridRes);
yGridRange = linspace(min(curveY) - 0.8, max(curveY) + 0.8, nGridRes);
[gridX, gridY] = meshgrid(xGridRange, yGridRange);
gridZ = fSurface(gridX, gridY);

%% ── 4. 生成柱面（积分"墙"）数据 ───────────────────────────────────────
%  vParam: 0(地面) → 1(曲面顶)，沿曲线逐点插值
vParam = linspace(0, 1, nWallLayers);
[tMesh, vMesh] = meshgrid(tRange, vParam);

wallX = tMesh;
wallY = sin(tMesh);
wallZ = vMesh .* fSurface(wallX, wallY);          % 从 0 渐变到曲面高度

%% ── 5. 计算积分墙面积的理论值（数值近似） ──────────────────────────────
ds = sqrt(gradient(curveX, tRange).^2 + gradient(curveY, tRange).^2);
ds = ds(:) * (tRange(2) - tRange(1));             % 弧微分
integralApprox = sum(surfaceHeight(:) .* ds);     % 数值积分

%% ── 6. 绘图 ────────────────────────────────────────────────────────────
fig = figure('Name', '第一型曲线积分几何意义', ...
             'Color', 'w', ...
             'Position', [80, 80, 900, 650], ...
             'NumberTitle', 'off');
hold on;

% ── 6a. 顶盖：半透明曲面 z = f(x,y) ──
surf(gridX, gridY, gridZ, ...
    'FaceAlpha', 0.25, ...
    'EdgeColor', 'none', ...
    'FaceColor', [0.05 0.45 0.80], ...
    'FaceLighting', 'gouraud', ...
    'SpecularStrength', 0.3);

% ── 6b. 底部：曲线 L 在 xy 平面上的投影 ──
plot3(curveX, curveY, curveZ, ...
    'LineWidth', 3.5, ...
    'Color', [0.15 0.15 0.15]);

% ── 6c. 顶部：曲线 L 贴合曲面 z = f(x,y) 的轨迹 ──
plot3(curveX, curveY, surfaceHeight, ...
    'LineWidth', 3.5, ...
    'Color', [0.82 0.15 0.18]);

% ── 6d. 填充条：曲线 L 正下方的 xy 平面带状条（增强投影感） ──
fill3([curveX, fliplr(curveX)], ...
      [curveY, fliplr(curveY)], ...
      [curveZ, fliplr(curveZ)], ...
      [0.2 0.2 0.2], ...
      'FaceAlpha', 0.15, 'EdgeColor', 'none');

% ── 6e. 柱面"墙"：∫_L f(x,y) ds 对应的面积 ──
surf(wallX, wallY, wallZ, ...
    'FaceAlpha', 0.75, ...
    'EdgeColor', 'none', ...
    'FaceColor', [0.82 0.67 0.25], ...
    'FaceLighting', 'gouraud', ...
    'SpecularStrength', 0.5, ...
    'DiffuseStrength', 0.7);

% ── 6f. 竖直线条：连接曲线 L 与其在曲面上的投影（增加立体感） ──
stripeIndices = round(linspace(1, nCurvePts, 18));
for idx = stripeIndices
    line([curveX(idx), curveX(idx)], ...
         [curveY(idx), curveY(idx)], ...
         [0,         surfaceHeight(idx)], ...
         'Color', [0.3 0.3 0.3], ...
         'LineWidth', 0.6, ...
         'LineStyle', ':');
end

%% ── 7. 光照与视角 ──────────────────────────────────────────────────────
light('Position', [2, -4, 8], 'Style', 'infinite', 'Color', [1 1 1] * 0.9);
light('Position', [-2, 3, 4], 'Style', 'infinite', 'Color', [1 1 1] * 0.4);
lighting gouraud;
view(-40, 28);
camproj('perspective');

%% ── 8. 坐标轴、标签与标题 ──────────────────────────────────────────────
axis tight;
xlabel('$x$', 'Interpreter', 'latex', 'FontSize', 14);
ylabel('$y$', 'Interpreter', 'latex', 'FontSize', 14);
zlabel('$z = f(x,\,y)$', 'Interpreter', 'latex', 'FontSize', 14);
title({'\bfseries 第一型曲线积分的几何意义：柱面面积'; ...
       ['$\displaystyle \int_{L} f(x,y)\,\mathrm{d}s \approx ', ...
        num2str(integralApprox, '%.2f'), '$']}, ...
       'Interpreter', 'latex', 'FontSize', 15);
set(gca, 'FontSize', 11, 'LineWidth', 1, 'Box', 'on');

%% ── 9. 图例与文字标注 ──────────────────────────────────────────────────
legend({'曲面 $z = f(x,y)$', ...
        '曲线 $L$ (底面投影)', ...
        '曲线 $L$ (曲面贴合)', ...
        '', ...
        '柱面面积 $\int_L f\,\mathrm{d}s$'}, ...
       'Location', 'northeast', ...
       'Interpreter', 'latex', ...
       'FontSize', 10.5, ...
       'Box', 'off');

%  标注柱面墙的面积
text(mean(curveX), mean(curveY), max(surfaceHeight) * 0.55, ...
     '\fontsize{12}\bf\downarrow 阴影面积 = 曲线积分值', ...
     'HorizontalAlignment', 'center', ...
     'BackgroundColor', 'w', ...
     'EdgeColor', [0.6 0.6 0.6], ...
     'Margin', 6);

%  标注曲面
text(curveX(end) + 0.15, curveY(end) + 0.5, ...
     fSurface(curveX(end), curveY(end)) + 0.6, ...
     '\fontsize{11}\color[rgb]{0.05,0.3,0.6}曲面 z = f(x,y)', ...
     'BackgroundColor', 'w', ...
     'EdgeColor', 'none');

%% ── 10. 保存图像 ──────────────────────────────────────────────────────
drawnow;
fprintf('积分近似值:  ∫_L f(x,y) ds ≈ %.4f\n', integralApprox);
fprintf('曲线弧长 L ≈ %.4f\n', sum(sqrt(gradient(curveX, tRange).^2 + gradient(curveY, tRange).^2)) * (tRange(2) - tRange(1)));
fprintf('图片已准备就绪，可手动保存为高分辨率格式。\n');
